kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: task-pv-claim-gitrepo
  annotations:
    volume.beta.kubernetes.io/storage-class: "nfs-dynamic"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
